### ISSUE TITLE
Default Browser encoding isn't UTF-8   had to add meta tag for 'â€¦' to change to '...'

### ISSUE THREAD

**Issue by mattbilodeau** [yowainwright/shave#1]
## What Is the issue?
  Without including  `<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />` in the Head, the `...` turn to     `â€¦`

## Provide issue context below using code examples, images, or links
without meta tag:
![image](https://user-images.githubusercontent.com/22197454/77687948-9fbc5c80-6f75-11ea-8f16-a346b0a247d2.png)

With meta tag:
![image](https://user-images.githubusercontent.com/22197454/77688014-bfec1b80-6f75-11ea-9d07-1fa3e895705d.png)

----

> Read about references issues [here](https://help.github.com/articles/closing-issues-using-keywords/). Provide paragraph text responses to each header.

**Comment by yowainwright** [comment]
@mattbilodeau will work on this asap.
