### ISSUE TITLE
Read-more link missing in options

### ISSUE THREAD

**Issue by karlbaumhauer** [yowainwright/shave#156]
## What Is the issue?
Text truncation is many times used to give a preview of longer text. To see the full text, read more links are usually added in the end of the text. 

## Suggestion
Adding an option to parse either an HTML string or link properties. HTML string can then provide web-components.

**Comment by karlbaumhauer** [comment]
I already pushed some suggestions for both solutions. Link properties works fine but I would love to be able to use web-components... there I am still struggling.

**Comment by yowainwright** [comment]
Hello @karlbaumhauer.  I saw your PRs. Thanks for your effort!!! (And great use of emojis 🎸 )

1. What do you think about the idea of defaulting to a `span` but allowing the implementor of `shave.js` to pass in an anchor element?
2. Following up with that approach. The implementor could optionally pass in attributes as they desire which could include link attributes (?).

---

**Quick note:** For most situations **now**, I recommend [line-clamp](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp) and `overflow: hidden` at a specified height. This covers almost every situation and browser without needing `Shave.js` and the extra JavaScript it is as well as dom thrashing it does. 

`Shave.js` uses binary search to optimize dom thrashing better than other text truncation libraries of its time. Shave.js was great when many customers were using older browsers before line-clamp. With line-clamp, I now, more than ever don't want to grow the scope of this utility but I do think we could default to an anchor tag with minimal effort. 

---

Post my rant 🙂 : 
- I'd love to hear about your use case (?) to ensure I understand your approach (?) and,
- I'd love to hear if you're open to making the change in your initial approach (?)
- there will need to be tests 🥇 

---

Thanks again!

**Comment by karlbaumhauer** [comment]
Hey @yowainwright,

Thanks for your quick response. 

**About my use case:**
I already used shave in a project but implemented a workround. After I finished it, I was not completely happy and started to work on a better solution.

My use case was a teaser group used for FAQ teasers. Each teaser has a headline (question) and a text preview of the answer. As each teaser in the teaser group has a fixed height but the headline can be single or multiple line and the rest of the teaser height is supposed to be filled with text and a read-more link to the FAQ detail page, I did not find any pure CSS solution. 

**About your questions:**
Unfortunately I do not get what you mean. Talking about the solution in #158 I pass properties in the options and this will add an anchor tag to the span... 

---------------

#157 would be the best way for me as I mostly work with web-components and therefore would need to pass a link-component.

**Comment by yowainwright** [comment]
Thanks for your explanation @karlbaumhauer!

1. I think the use case you wrote could be written with CSS and a toggling class. I'll leave that to you. 🙂 
2. Rather than assuming [this](https://github.com/yowainwright/shave/blob/master/src/shave.js#L10) should be a span, perhaps it could be a span or anchor tag using `document.createElemement(el)`.
3. From there, element attributes could be passed in.

^ A solution like that (2 and 3) might be approved if it was opinionated enough. 
- The goal of this utility is to be fast, not feature-rich. 👌 

Thanks again!

**Comment by yowainwright** [comment]
@karlbaumhauer sorry! I realize my last comment (which I updated) was unclear **and** I didn't have a question. 

So what do you think about my comment?

Thanks!

**Comment by karlbaumhauer** [comment]
@yowainwright sorry to let you wait for my answer. I am pretty busy right now. 

nevertheless I pushed some new changes and hope this was what you expected to see... 😥  😉

to your previous post:

I tried a lot with CSS and in my use case we had to have a flexible height of both elements inside the teaser container. This leads to the point that I had to rebuild the truncation on resize... not really nice and the component has not been approved (due to UX decisions) but it worked in the end... therefore I was into making this use case possible with your plugin.

Nevertheless I totally understand your goal and thought a lot about it the last days. I really like it maybe it will be a second package I will publish on npm with those kind of features. But I will leave it up to you.

what do you think?

**Comment by yowainwright** [comment]
@karlbaumhauer 

1. As you've been so thoughtful, I'll try to past a solution of what I'd generally do today. 
2a. I'm **all** for making a package that suits your needs and potentially provides others with exactly what they may want/need! I do recommend using the binary search pattern to reduce dom thrashing. That is/was the big win with this **shave.js**.
2b. I may be able to assist here to make the update a bit smaller and also make the jump to typescript. I'll see if I have time to go for it this week. 

Thanks again @karlbaumhauer !

**Comment by yowainwright** [comment]
@karlbaumhauer my bad. I'm switching jobs right now so I'm doing live admin things.
