### ISSUE TITLE
What's the advantage of using `shave` over Bootstrap 5 `text-truncate` for instance 

### ISSUE THREAD

**Issue by bacloud22** [yowainwright/shave#224]
## Bootstrap 5 offers Text truncation

[Text truncation](https://getbootstrap.com/docs/5.0/helpers/text-truncation/) truncate long strings of text with an ellipsis.
Besides that shave maintains the original text after truncation (but I don't need that);

thanks a lot

**Comment by yowainwright** [comment]
@bacloud22 from previous testing, Shave was a bit faster than other js libs for text truncation. I have tested in a while so I don't know if there are faster libraries out. 

However, to your point (and unrelated to Bootstrap) CSS can support text truncation with [line-clamp](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp) or [text-overflow ellipsis](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow). 

Shave still might be useful for adding links or to support older browsers. 👍

**Comment by bacloud22** [comment]
Thank you @yowainwright for the valuable work. I was asking because yes I'm trying to make a website the would like preferably to support most browsers. I 'll give it a try. 

Thanks 🙏
