### ISSUE TITLE
Small issue: Return type is missing in index.d.ts

### ISSUE THREAD

**Issue by Crefelder** [yowainwright/shave#239]
## What Is the issue?
Using shape Angular 13.3.8 in strict mode.
At ng build there is a compile error:
Error: node_modules/shave/types/index.d.ts:6:25 - error TS7010: 'shave', which lacks return-type annotation, implicitly has an 'any' return type.
![image](https://user-images.githubusercontent.com/7198153/168301602-998c3ee9-f960-44c7-8f5e-a3b4528cf990.png)

## Provide issue context below using code examples, images, or links
ng build or npm run build in Angular project with strict mode on.
ng generate application [project-name] --strict
& npm package "shave": "^4.0.0",

**For me it is currently helping to add only ": any"**
**in "node_modules/shave/types/index.d.ts" like this:**

![image](https://user-images.githubusercontent.com/7198153/168301126-b761b837-8ec5-4e0c-9e8d-a15b4f126257.png)

**Comment by yowainwright** [comment]
Thanks @Crefelder ! I'll look asap! Sorry for this!
