### ISSUE TITLE
Ellipsis character is only added to final element

### ISSUE THREAD

**Issue by brandonjp** [yowainwright/shave#246]
## What Is the issue?

When I use a selector that collects multiple elements:
`shave('.shave-this', 90);`
All texts are truncated, but the ellipsis character is only added to the final element. 

See a code example here:  https://jsbin.com/luxuzar/2/edit?html,js,output

<img width="842" alt="CleanShot 2022-07-14 at 07 45 59@2x" src="https://user-images.githubusercontent.com/199599/178985651-0bbd418e-a6f6-45ab-a1b3-a72d0376398c.png">

----

> Read about references issues [here](https://help.github.com/articles/closing-issues-using-keywords/). Provide paragraph text responses to each header.

**Comment by brandonjp** [comment]
Just noticed that using `@version v2.5.7 ` from https://github.com/dollarshaveclub/shave/blob/master/dist/shave.min.js does work as expected.  And `@version v3.0.0-beta.0` at https://raw.githubusercontent.com/yowainwright/shave/70981e9d7b3311086331949fbe95f620cc3029dc/dist/shave.js also works as expected. 

My tests were with the latest `@version v4.0.0` at https://github.com/yowainwright/shave/blob/086aba6c773f730f072595e3bab9f74865a26dd1/dist/shave.js

**Comment by yowainwright** [comment]
Whoa! Thanks @brandonjp! 

I'll look tomorrow. I apologize for not seeing this sooner.

**Comment by yowainwright** [comment]
This issue is **valid**—and deeply related to #242 ! 🎉
