### ISSUE TITLE
Is there a way to know whether shave has truncated the text or not?

### ISSUE THREAD

**Issue by ankitskvmdam** [yowainwright/shave#258]
## What Is the issue?

At the moment, I guess there is no way to find whether we have truncated a text. There are a few use cases when we are required to have this information. For example, if we want to show a tooltip when we have truncated a text.

I think, shave should return a response object that has the following structure:
```ts
// Shave response object.
type TShaveResponse = {
    // True if shave has truncated the original text
    didTruncate: boolean
    // original text.
    originalText: string
   // truncated text
   truncatedText: string
}
```

**Comment by yowainwright** [comment]
The css class is only added to shaved items. 
So you can, write some code based on that. 
Maybe even no JavaScript!

In example
```css
.js-shave .tooltip:hover {
  display: block;
}
```
