### ISSUE TITLE
Links and styles in the text are not preserved.  Tags are stripped.

### ISSUE THREAD

**Issue by bs-thomas** [yowainwright/shave#285]
Hello there, 

I noticed that the target element's links or styles are not preserved after truncation.  The HTML tags inside are stripped.  I switched over from an old library called dotdotdot().

Behavior was a bit different but there was no way for me to make a "non-breaking" upgrade to shave, because shave removes all links and styles in the original text.

This is the output from dotdotdot:
![image](https://user-images.githubusercontent.com/2464920/212741776-0131e9be-49e0-4af5-a69a-4c5818e57b52.png)

This is the output from shave:
![image](https://user-images.githubusercontent.com/2464920/212741910-65b36775-2ff1-4c98-9309-e3d94e565900.png)

I was wondering if it is possible to preserve these links and styles after truncation?

Thank you very much!!

**Comment by bs-thomas** [comment]
#286

**Comment by bs-thomas** [comment]
Added new option persistHtml.
It's a non-breaking change.

Usage as follows:

`shave(el, maxHeight, {spaces: false, persistHtml: true});`

Would you please kindly merge over if possible, as I'll be needing this option for one of my production sites?

Thank you very much!

**Comment by yowainwright** [comment]
@bs-thomas this is [by design](https://github.com/dollarshaveclub/shave/pull/41)! 
Feel free to search Shave's commit history [in this project's original repository](https://github.com/dollarshaveclub/shave) for more insight.

Thanks for submitting the issue and PR!
