### ISSUE TITLE
Incompatible with css modules?

### ISSUE THREAD

**Issue by TheAyes** [yowainwright/shave#382]
## What Is the issue?
So... either I'm doing it wrong or your function seems to be incompatible with css modules.
As soon as I involve a module reference the code stop workingif I remove that reference and only use "p" as a selector. The code works fine. But I don't want to literally shave every p. I only want to shave the p inside of my component, which has this modue class.

I've verified the existence of this class and also checked if it's using that class in the function.

## Provide issue context below using code examples, images, or links
Here's my component:
```jsx
import { FC, useEffect } from "react";
import shave from "shave";
import ActionButtonStyles from "./ActionButton.module.scss";

export interface IActionButton {
	size: "small" | "medium" | "large";
	caption: string;
	imgUrl: string;

	[key: string]: any;
}

export const ActionButton: FC<IActionButton> = ({ size, caption = "Some Button", imgUrl, ...remainingProps }) => {
	const isCaptionVisible = size !== "small";

	useEffect(() => {
		shave(`${ActionButtonStyles.ActionButton} p`, 30);
	}, []);

	const Caption = () => {
		if (isCaptionVisible) {
			return <p>{caption}</p>;
		}
		return null;
	};

	return (
		<button {...remainingProps} className={`${ActionButtonStyles.ActionButton} ${ActionButtonStyles[size]}`}>
			<img width={50} height={50} src="" alt="" />
			<Caption />
		</button>
	);
};
```

**Comment by TheAyes** [comment]
For now I've worked around it adding a class specific to this component.

```
<p className="ActionButtonCaption-Shave">{caption}</p>
```

and then just use that to select the element.

**Comment by yowainwright** [comment]
I don't feel the solution above in the second comment is a work-around. Nice work! 🙌

**Comment by TheAyes** [comment]
Well, it's kinda defeating the point of using css modules in the first place.
